language: python
python: "3.5"
install: pip install -r requirements.txt
script:
  - pylint
  - coverage run python -m unittest -s ./tests
  - coverage report --fail-under 100
  - sphinx-build -nW -b html -d _build/doctrees . _build/html
