language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - pylint geometrylib
  - coverage run --include geometrylib/* ./manage.py test
  - coverage report --fail-under 100
  - sphinx-build -nW -b html -d docs/build/doctrees . docs/build/html
